spring.application.name=campus-navigation

//database

spring.datasource.url=jdbc:mysql://localhost:3306/campus-navigation
spring.datasource.username=root
spring.datasource.password=divyanshu002@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
